<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<FileVersion>2024.4</FileVersion>
		<ProductVersion>2024.4</ProductVersion>
		<Version>2024.4</Version>
		<AssemblyName>UncertainLuei.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>UncertainLuei.BaldiPlus.$(MSBuildProjectName)</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.AssemblyPublicizer" Version="0.4.2" />
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath>..\Dependencies\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp" Publicize="true">
			<HintPath>..\Dependencies\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="MTM101BaldApi.dll">
			<HintPath>..\Dependencies\MTM101BaldApi.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx">
			<HintPath>..\Dependencies\BepInEx.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx.Harmony">
			<HintPath>..\Dependencies\BepInEx.Harmony.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>..\Dependencies\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>..\Dependencies\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\Dependencies\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ImageConversionModule">
			<HintPath>..\Dependencies\UnityEngine.ImageConversionModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>..\Dependencies\UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIModule">
			<HintPath>..\Dependencies\UnityEngine.UIModule.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
