<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		
		<AssemblyName>UncertainLuei.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>UncertainLuei.$(MSBuildProjectName)</RootNamespace>
		
		<Version>2025.3.1</Version>
		<FileVersion>$(Version)</FileVersion>
		<ProductVersion>$(Version)</ProductVersion>
		
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<NoWarn>1701;1702;IDE0017;IDE0051</NoWarn>

		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json;
			https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
		<PackageReference Include="BepInEx.Core" Version="5.*" />
		<PackageReference Include="Hamunii.BepInEx.AutoPlugin" Version="2.*" />
		<PackageReference Include="UnityEngine.Modules" Version="2020.3.38" IncludeAssets="compile" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />

		<PackageReference Include="BepInEx.AssemblyPublicizer" Version="0.4.2" />
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath>..\Dependencies\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp" Publicize="true">
			<HintPath>..\Dependencies\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="MTM101BaldAPI" Publicize="true">
			<HintPath>..\Dependencies\MTM101BaldAPI.dll</HintPath>
		</Reference>
		<Reference Include="BetterChalkboardFont" Publicize="true">
			<HintPath>..\Dependencies\BetterChalkboardFont.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx">
			<HintPath>..\Dependencies\BepInEx.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx.Harmony">
			<HintPath>..\Dependencies\BepInEx.Harmony.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>..\Dependencies\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>..\Dependencies\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\Dependencies\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ImageConversionModule">
			<HintPath>..\Dependencies\UnityEngine.ImageConversionModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>..\Dependencies\UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIModule">
			<HintPath>..\Dependencies\UnityEngine.UIModule.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
